-- ==============================================================================
-- AI CLUB - Milestone 6: Events Seed Fixtures
-- File: seed_m6_events.sql
-- Description: Realistic event fixtures across categories and statuses
-- ==============================================================================

INSERT INTO public.events (
    id,
    title,
    slug,
    short_description,
    description,
    category,
    event_mode,
    location,
    is_online,
    meeting_url,
    start_at,
    end_at,
    registration_open_at,
    registration_close_at,
    capacity,
    eligibility,
    status,
    speaker,
    organizer,
    tags,
    published_at
) VALUES
(
    '00000000-0000-0000-0000-000000000601',
    'AI Systems Bootcamp 2026',
    'ai-systems-bootcamp-2026',
    'Hands-on intensive workshop building neural architectures from first principles with PyTorch.',
    'Join our senior AI research fellows for a 2-day intensive bootcamp covering tensor operations, autograd engines, transformer self-attention blocks, and GPU acceleration. Participants will build and train a mini-GPT from scratch.',
    'bootcamp',
    'physical',
    'AI Club Research Lab, Innovation Block 4',
    false,
    null,
    NOW() + INTERVAL '10 days',
    NOW() + INTERVAL '12 days',
    NOW() - INTERVAL '5 days',
    NOW() + INTERVAL '9 days',
    60,
    'members_only',
    'published',
    'Dr. Aris Thorne (Lead AI Researcher)',
    'AI Club Engineering Core',
    ARRAY['PyTorch', 'Deep Learning', 'Transformers', 'GPU'],
    NOW() - INTERVAL '5 days'
),
(
    '00000000-0000-0000-0000-000000000602',
    'Autonomous Agents Hackathon 2026',
    'autonomous-agents-hackathon-2026',
    '48-hour collaborative buildathon engineering multi-agent systems and tool-using LLMs.',
    'The premier autumn hackathon challenging teams to design resilient, production-ready agentic loops. Mentors will be present throughout the weekend, providing cloud compute credits and guidance on tool calling, memory management, and guardrails.',
    'hackathon',
    'hybrid',
    'Main Auditorium & Discord',
    true,
    'https://meet.aiclub.internal/hackathon-2026',
    NOW() + INTERVAL '20 days',
    NOW() + INTERVAL '22 days',
    NOW() - INTERVAL '2 days',
    NOW() + INTERVAL '19 days',
    120,
    'members_only',
    'published',
    'Guest Industry Mentors',
    'AI Club Innovation Committee',
    ARRAY['Multi-Agent', 'Hackathon', 'LLM', 'Competition'],
    NOW() - INTERVAL '2 days'
),
(
    '00000000-0000-0000-0000-000000000603',
    'Frontiers of Generative Models Tech Talk',
    'frontiers-of-generative-models-tech-talk',
    'Technical deep dive into diffusion models, flow matching, and multimodal synthesis.',
    'An evening keynote exploring the mathematical underpinnings of diffusion probabilities, continuous normalizing flows, and recent breakthroughs in multimodal latent models.',
    'tech_talk',
    'online',
    null,
    true,
    'https://meet.aiclub.internal/tech-talk-generative',
    NOW() + INTERVAL '5 days',
    NOW() + INTERVAL '5 days 2 hours',
    NOW() - INTERVAL '10 days',
    NOW() + INTERVAL '4 days 23 hours',
    200,
    'members_only',
    'published',
    'Priya Ramanathan (Staff ML Engineer)',
    'AI Club Research Forum',
    ARRAY['Diffusion', 'Mathematics', 'Tech Talk'],
    NOW() - INTERVAL '10 days'
),
(
    '00000000-0000-0000-0000-000000000604',
    'Computer Vision Foundations Workshop',
    'computer-vision-foundations-workshop',
    'Past workshop covering convolutional backbones, object detection, and segmentation.',
    'A foundational workshop held earlier this semester exploring visual feature extraction, YOLO architectures, and practical inference on edge devices.',
    'workshop',
    'physical',
    'Computer Vision Lab 102',
    false,
    null,
    NOW() - INTERVAL '20 days',
    NOW() - INTERVAL '19 days',
    NOW() - INTERVAL '35 days',
    NOW() - INTERVAL '21 days',
    40,
    'members_only',
    'completed',
    'Kavya Sundaram',
    'AI Club Education Guild',
    ARRAY['Computer Vision', 'YOLO', 'OpenCV'],
    NOW() - INTERVAL '35 days'
)
ON CONFLICT (slug) DO NOTHING;
